version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    working_directory: ~/Hardcode-Tray
    steps:
      - run: >
          apt install -y gettext gir1.2-gtk-3.0 gobject-introspection libffi6
          libgtk-3-dev meson ninja-build pylint python3-cffi python3-gi
          python3-gi-cairo python3-jsonschema
      - checkout
      - run: meson builddir
      - run: ninja -C builddir install
      - run: python3 ./tests/database/database.py
      - run: sh ./tests/pylint.sh
