version: 2
jobs:
  build:
    docker:
      - image: ubuntu:rolling
    working_directory: ~/Hardcode-Tray
    steps:
      - run: >
          apt update && DEBIAN_FRONTEND=noninteractive apt -y
          --no-install-recommends install gettext libgirepository1.0-dev
          libgtk-3-dev meson pylint python3-cffi python3-gi-cairo
          python3-jsonschema && DEBIAN_FRONTEND=noninteractive apt -y
          full-upgrade
      - checkout
      - run: meson builddir
      - run: ninja -C builddir install
      - run: python3 ./tests/database/database.py
      - run: sh ./tests/pylint.sh
